/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/schedule'
    | '/sitemap.xml'
    | '/history'
    | '/profile'
    | '/watchlist'
    | '/anime/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/schedule'
    | '/sitemap.xml'
    | '/history'
    | '/profile'
    | '/watchlist'
    | '/anime/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/schedule'
    | '/sitemap.xml'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/watchlist'
    | '/anime/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnimeIdRoute: typeof AnimeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnimeIdRoute: AnimeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
